services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: laandry
      POSTGRES_PASSWORD: laandry
      POSTGRES_DB: laandry
    ports:
      - "5432:5432"
    volumes:
      - laandry_postgres_data:/var/lib/postgresql/data

volumes:
  laandry_postgres_data:
